[context.production.environment]
    HUGO_VERSION = "0.30.2"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.30.2"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"